db:
  type: postgres
  host: localhost
  port: 5432
  user: postgres
  pass: changeme
  name: qrs
  pool:
    max_conn: 16
    min_conn: 4
    max_conn_idle_time: 3m
    max_conn_lifetime: 3m
    health_check_period: 1m
